# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{operawatir}
  s.version = "0.2.19"
  s.platform = %q{jruby}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Deniz Turkoglu", "Andreas Tolf Tolfsen", "Chris Lloyd", "Adam Minchinton", "Karianne Ekern"]
  s.date = %q{2011-01-20}
  s.description = %q{OperaWatir on OperaDriver engine}
  s.email = ["dturkoglu@opera.com", "andreastt@opera.com", "christopherl@opera.com", "adamm@opera.com", "karie@opera.com"]
  s.executables = ["desktopwatir", "operawatir"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitmodules",
    "AUTHORS",
    "Gemfile",
    "INSTALL",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/desktopwatir",
    "bin/operawatir",
    "lib/operadriver/commons-jxpath-1.3.jar",
    "lib/operadriver/protobuf-java-2.3.0.jar",
    "lib/operadriver/selenium-common.jar",
    "lib/operadriver/webdriver-opera.jar",
    "lib/operawatir.rb",
    "lib/operawatir/browser.rb",
    "lib/operawatir/collections.rb",
    "lib/operawatir/desktop-waiter.rb",
    "lib/operawatir/desktop_browser.rb",
    "lib/operawatir/desktop_common.rb",
    "lib/operawatir/desktop_container.rb",
    "lib/operawatir/desktop_enums.rb",
    "lib/operawatir/desktop_exceptions.rb",
    "lib/operawatir/elements.rb",
    "lib/operawatir/elements/button.rb",
    "lib/operawatir/elements/checkbox.rb",
    "lib/operawatir/elements/element.rb",
    "lib/operawatir/elements/file_field.rb",
    "lib/operawatir/elements/form.rb",
    "lib/operawatir/elements/image.rb",
    "lib/operawatir/elements/link.rb",
    "lib/operawatir/elements/non_control_elements.rb",
    "lib/operawatir/elements/radio.rb",
    "lib/operawatir/elements/select_list.rb",
    "lib/operawatir/elements/text_field.rb",
    "lib/operawatir/elements/web_element.rb",
    "lib/operawatir/exceptions.rb",
    "lib/operawatir/helper.rb",
    "lib/operawatir/platform.rb",
    "lib/operawatir/quickwidgets.rb",
    "lib/operawatir/quickwidgets/quick_addressfield.rb",
    "lib/operawatir/quickwidgets/quick_button.rb",
    "lib/operawatir/quickwidgets/quick_checkbox.rb",
    "lib/operawatir/quickwidgets/quick_dialogtab.rb",
    "lib/operawatir/quickwidgets/quick_dropdown.rb",
    "lib/operawatir/quickwidgets/quick_editfield.rb",
    "lib/operawatir/quickwidgets/quick_label.rb",
    "lib/operawatir/quickwidgets/quick_radiobutton.rb",
    "lib/operawatir/quickwidgets/quick_searchfield.rb",
    "lib/operawatir/quickwidgets/quick_tab.rb",
    "lib/operawatir/quickwidgets/quick_toolbar.rb",
    "lib/operawatir/quickwidgets/quick_treeitem.rb",
    "lib/operawatir/quickwidgets/quick_treeview.rb",
    "lib/operawatir/quickwidgets/quick_widget.rb",
    "lib/operawatir/quickwidgets/quick_window.rb",
    "lib/operawatir/version.rb",
    "spec/fire_event/fire_event.rb",
    "spec/fire_event/interactive/onBlur.html",
    "spec/fire_event/interactive/onChange.html",
    "spec/fire_event/interactive/onClick.html",
    "spec/fire_event/interactive/onDblClick.html",
    "spec/fire_event/interactive/onFocus.html",
    "spec/fire_event/interactive/onMouseDown.html",
    "spec/fire_event/interactive/onMouseMove.html",
    "spec/fire_event/interactive/onMouseOut.html",
    "spec/fire_event/interactive/onMouseOver.html",
    "spec/fire_event/interactive/onMouseUp.html",
    "spec/fire_event/interactive/onScroll.html",
    "spec/spec_helper.rb",
    "utils/Rakefile",
    "utils/formatters/operahelper_formatter.rb",
    "utils/formatters/spartan_formatter.rb",
    "utils/inspectr",
    "utils/inspectr.exe",
    "utils/launchers/launcher-linux-i686",
    "utils/launchers/launcher-linux-x86_64",
    "utils/launchers/launcher-win32-i86pc.exe"
  ]
  s.homepage = %q{http://opera.github.com/operawatir}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{operawatir}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{OperaWatir on OperaDriver engine}
  s.test_files = [
    "spec/fire_event/fire_event.rb",
    "spec/new_watirspec/browser_spec.rb",
    "spec/new_watirspec/collection_spec.rb",
    "spec/new_watirspec/element_spec.rb",
    "spec/new_watirspec/guards.rb",
    "spec/new_watirspec/lib/guards.rb",
    "spec/new_watirspec/lib/implementation.rb",
    "spec/new_watirspec/lib/runner.rb",
    "spec/new_watirspec/lib/server.rb",
    "spec/new_watirspec/lib/watirspec.rb",
    "spec/new_watirspec/server.rb",
    "spec/new_watirspec/watirspec_helper.rb",
    "spec/new_watirspec/window_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0.6.3"])
      s.add_development_dependency(%q<rspec>, ["= 2.0.1"])
      s.add_development_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_development_dependency(%q<mongrel>, [">= 1.1.5"])
      s.add_development_dependency(%q<rr>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<rspec>, ["= 2.0.1"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<mongrel>, [">= 1.1.5"])
      s.add_development_dependency(%q<sinatra>, [">= 1.1"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0.6.3"])
      s.add_dependency(%q<rspec>, ["= 2.0.1"])
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<mongrel>, [">= 1.1.5"])
      s.add_dependency(%q<rr>, [">= 1.0.2"])
      s.add_dependency(%q<rspec>, ["= 2.0.1"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<mongrel>, [">= 1.1.5"])
      s.add_dependency(%q<sinatra>, [">= 1.1"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0.6.3"])
    s.add_dependency(%q<rspec>, ["= 2.0.1"])
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<mongrel>, [">= 1.1.5"])
    s.add_dependency(%q<rr>, [">= 1.0.2"])
    s.add_dependency(%q<rspec>, ["= 2.0.1"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<mongrel>, [">= 1.1.5"])
    s.add_dependency(%q<sinatra>, [">= 1.1"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

